# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Bayesian Doctor
tagline:          'Hello.'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://ljenglish.net
baseurl:          /

author:
  name:           'Luke English'
  url:            https://twitter.com/lj_english

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Windows nonsense (probably)
gems:             [jekyll-paginate]
