# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Bayesian Doctor
tagline:          'Hello.'
description:      'I want to be a better person for the betterment of the world.'
url:              http://ljenglish.net
baseurl:          /

author:
  name:           'Luke English'
  url:            https://twitter.com/lj_english

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fourtyfour-saka/fourtyfour-saka.github.io

# Windows nonsense (probably)
gems:             [jekyll-paginate]
